version: "3.9"

services:
  poster:
    image: 'ghcr.io/inst-api/poster:latest'
    restart: unless-stopped
    ports:
      - "8090:8090" # REST
    #    healthcheck:
    #      test: ['CMD', 'curl', '-f', 'http://localhost:8000/live']
    #      interval: 1m
    #      timeout: 10s
    #      retries: 3
    #      start_period: 20s
    volumes:
      - tmp_logs:/root/tmp
      - ./videos:/root/videos
    networks:
      - postgres_ompnw
  api:
    image: 'ghcr.io/inst-api/poster.python-api:latest'
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./instagrapi-rest:/app
    networks:
      - postgres_ompnw
networks:
  postgres_ompnw:
    driver: bridge
    external: true

volumes:
  tmp_logs:
    name: poster_logs
    driver: local