version: "3.9"

services:
  migration:
    build:
      context: .
      dockerfile: migration.Dockerfile
    environment:
      - ENVIRONMENT
    entrypoint: "/home/app/scripts/migrate.sh"

networks:
  default:
    external: true
    name: routingappservice_ompnw