version: "3.7"

services:
  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: insta_poster