swagger: "2.0"
info:
  title: REST api for simple route app
  version: ""
host: /
consumes:
  - application/json
  - application/xml
  - application/gob
produces:
  - application/json
  - application/xml
  - application/gob
paths:
  /api/admin/driver:
    post:
      tags:
        - admin_service
      summary: add_manager admin_service
      description: |-
        admins could add drivers from main system

        **Required security scopes for jwt**:
          * `admin`
      operationId: admin_service#add_manager
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: false
          type: string
        - name: add_manager_request_body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AdminServiceAddManagerRequestBody'
            required:
              - login
              - password
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "403":
          description: Forbidden response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/admin/driver/{manager_id}:
    delete:
      tags:
        - admin_service
      summary: drop_manager admin_service
      description: |-
        admins could delete managers from main system

        **Required security scopes for jwt**:
          * `admin`
      operationId: admin_service#drop_manager
      parameters:
        - name: manager_id
          in: path
          description: id менеджера, которого необходимо удалить
          required: true
          type: string
          format: uuid
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: false
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "403":
          description: Forbidden response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/profile:
    get:
      tags:
        - auth_service
      summary: profile auth_service
      description: get user profile
      operationId: auth_service#profile
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/signin:
    post:
      tags:
        - auth_service
      summary: signin auth_service
      description: Creates a valid JWT
      operationId: auth_service#signin
      parameters:
        - name: Authorization
          in: header
          description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuthServiceSigninResponseBody'
            required:
              - jwt
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - basic_header_Authorization: []
  /api/tasks/:
    get:
      tags:
        - tasks_service
      summary: list tasks tasks_service
      description: получить все задачи для текущего пользователя
      operationId: tasks_service#list tasks
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
    post:
      tags:
        - tasks_service
      summary: create task tasks_service
      description: создать драфт задачи
      operationId: tasks_service#create task
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
        - name: Create TaskRequestBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/TasksServiceCreateTaskRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: string
            format: uuid
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/:
    get:
      tags:
        - tasks_service
      summary: get task tasks_service
      description: получить задачу по id
      operationId: tasks_service#get task
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/start:
    post:
      tags:
        - tasks_service
      summary: start task tasks_service
      description: 'начать выполнение задачи '
      operationId: tasks_service#start task
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/upload:
    post:
      tags:
        - tasks_service
      summary: upload file tasks_service
      description: загрузить файл с пользователями, прокси
      operationId: tasks_service#upload file
      consumes:
        - multipart/form-data
      parameters:
        - name: task_id
          in: path
          description: id задачи, в которую загружаем пользователей/прокси
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
        - name: Upload FileRequestBody
          in: formData
          required: true
          schema:
            $ref: '#/definitions/TasksServiceUploadFileRequestBody'
            required:
              - file_type
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
definitions:
  AdminServiceAddManagerRequestBody:
    title: AdminServiceAddManagerRequestBody
    type: object
    properties:
      login:
        type: string
        example: Nam quis quaerat exercitationem.
      password:
        type: string
        example: 15z
        minLength: 4
    example:
      login: Sit mollitia voluptatibus aperiam ut necessitatibus et.
      password: mxy
    required:
      - login
      - password
  AuthServiceSigninResponseBody:
    title: AuthServiceSigninResponseBody
    type: object
    properties:
      jwt:
        type: string
        description: JWT token
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
    example:
      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
    required:
      - jwt
  TasksServiceCreateTaskRequestBody:
    title: TasksServiceCreateTaskRequestBody
    type: object
    properties:
      description:
        type: string
        description: описание задачи
        example: Labore nihil.
      tittle:
        type: string
        description: название задачи
        example: Modi quo repellat nam quasi velit.
    example:
      description: Laboriosam sit et id nisi.
      tittle: Labore et ex ab laudantium officia quia.
  TasksServiceUploadFileRequestBody:
    title: TasksServiceUploadFileRequestBody
    type: object
    properties:
      bytes:
        type: string
        description: содержимое файла
        example:
          - 83
          - 117
          - 110
          - 116
          - 32
          - 118
          - 101
          - 114
          - 111
          - 32
          - 105
          - 100
          - 46
        format: byte
      file_type:
        type: integer
        description: |2-
           1 - список ботов
              2 - список резидентских прокси
              3 - спиок прокси-шестёрок
        example: 1
        enum:
          - 1
          - 2
          - 3
    example:
      bytes:
        - 73
        - 116
        - 97
        - 113
        - 117
        - 101
        - 32
        - 109
        - 111
        - 108
        - 101
        - 115
        - 116
        - 105
        - 97
        - 101
        - 32
        - 115
        - 111
        - 108
        - 117
        - 116
        - 97
        - 32
        - 113
        - 117
        - 97
        - 101
        - 32
        - 97
        - 100
        - 105
        - 112
        - 105
        - 115
        - 99
        - 105
        - 32
        - 109
        - 111
        - 100
        - 105
        - 32
        - 100
        - 111
        - 108
        - 111
        - 114
        - 46
      file_type: 1
    required:
      - file_type
securityDefinitions:
  basic_header_Authorization:
    type: basic
    description: |-
      Basic authentication used to authenticate security principal during signin

      **Security Scopes**:
        * `driver`: Read-only access
  jwt_header_Authorization:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".

      **Security Scopes**:
        * `driver`: Read-only access
        * `admin`: Read and write access
    name: Authorization
    in: header
