listen:
  port: 8090
  bind_ip: 0.0.0.0
  parser_url: parser:9091
logger:
  enable console: true
  console json format: true
  console level: info
  enable file: true
  file json format: true
  file level: debug
  file location: ./tmp/logs.log
postgres:
  host: postgres
  port: 5432
  migration_host: localhost
  migration_port: 5435
  user: postgres
  password: postgres
  database: insta_poster
  ssl mode: disable
  migrations dir: migrations
  pg-dsn: "postgres://postgres@postgres:5432/insta_poster?sslmode=disable&timezone=utc"
instagrapi:
  hostname: 'http://api:8000'
session:
  JWT signing key: "simple route is the best routing soft ever"
  token validness duration: 24h