listen:
  port: 8090
  bind_ip: 127.0.0.1
  cert_file: 'localhost.crt'
  key_file: 'localhost.key'
logger:
  enable console: true
  console json format: true
  console level: info
  enable file: true
  file json format: true
  file level: debug
  file location: ./tmp/logs.log
postgres:
  host: localhost
  port: 5432
  migration_host: localhost
  migration_port: 5432
  user: postgres
  password: postgres
  database: insta_poster
  ssl mode: disable
  migrations dir: migrations
#  used for goose migrations
  pg-dsn: "postgres://postgres@localhost:5432/insta_poster?sslmode=disable&timezone=utc"
session:
  JWT signing key: "simple route is the best routing soft ever"
  token validness duration: 24h