listen:
  port: 8090
  bind_ip: 127.0.0.1
  insta_proxy_url: 127.0.0.1:8092
  cert_file: 'localhost.crt'
  key_file: 'localhost.key'
logger:
  enable console: true
  console json format: true
  console level: info
  enable file: true
  file json format: true
  file level: debug
  file location: ./tmp/logs.log
postgres:
  port: 5432
  host: localhost
  user: postgres
  password: postgres
  
  #  prod users
#  host: 65.109.30.237
#  user: docker
#  password: dN5mYdDVKbuyq6ry
  
  migration_host: localhost
  migration_port: 5432
  database: insta_poster
  ssl mode: disable
  migrations dir: migrations
  #  used for goose migrations
  pg-dsn: "postgres://postgres@localhost:5432/insta_poster?sslmode=disable&timezone=utc"
session:
  JWT signing key: "simple route is the best routing soft ever"
  token validness duration: 24h