name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check changed files
    outputs:
      api_service: ${{ steps.check_files.outputs.api_service }}
      note_service: ${{ steps.check_files.outputs.note_service }}
      category_service: ${{ steps.check_files.outputs.category_service }}
      file_service: ${{ steps.check_files.outputs.file_service }}
      tag_service: ${{ steps.check_files.outputs.tag_service }}
      user_service: ${{ steps.check_files.outputs.user_service }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == api_service/* ]]; then
              echo "::set-output name=api_service::true"
            elif [[ $file == note_service/* ]]; then
              echo "::set-output name=note_service::true"
            elif [[ $file == category_service/* ]]; then
              echo "::set-output name=category_service::true"
            elif [[ $file == file_service/* ]]; then
              echo "::set-output name=file_service::true"
            elif [[ $file == tag_service/* ]]; then
              echo "::set-output name=tag_service::true"
            elif [[ $file == user_service/* ]]; then
              echo "::set-output name=user_service::true"
            else
              echo "file does not belong to any service"
            fi
          done < files.txt
  api_service:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: 'ghcr.io'
          username: 'vulp1x'
          password: ${{ secrets.PAT }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'inst-api/poster:latest'

      - name: Publish to Registry inst-api
        uses: docker/build-push-action@v2
        with:
          context: ./instagrapi-rest
          push: true
          tags: 'inst-api/poster.python-api:latest'

      - name: Execute remote ssh command using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/poster
            docker-compose down
            docker pull vulp1x/inst-api.poster:latest
            docker-compose -f docker-compose.yaml up --detach